### ISSUE TITLE
Publish a pip package

### ISSUE THREAD

**Issue by jjmontesl** [wyldebeast-wunderliebe/incf.countryutils#2]
Current package in PyPI has no Python 2.7 support, your version does. Thanks for this.

Could you please publish this so it can be used as a dependency for Python 3 projects?

**Comment by isac322** [comment]
@huubbouma Do you need any help? I want to use this package on Python 3.

**Comment by huubbouma** [comment]
I created a pypi package, and added a 2 as suffix, since I don't own the original package
https://pypi.org/project/incf.countryutils2
